server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5434/notification
    username: 'root'
    password: 'root'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true